// Generated by CoffeeScript 1.4.0
(function() {
   
  Template.registerHelper('encode',function(str){
	 return encodeURIComponent(str);
  });
  Template.registerHelper('equals', function (a, b) {
      return a === b;
    });

    Template.registerHelper('log',function(whatever){
        console.log(whatever);
    });
  
  Template.registerHelper('tableValue',function(column,item) { 
	  var val = item[column.id];
	  if(column.view)
		return column.view(val);
	  return val;
  });
  
  Template.registerHelper('workOrderStage',function(name) {
	var stage = WorkOrders.Stages[name];
	if(!stage)
		return '';
	return stage.label;
  });
  Template.registerHelper('pictureURL',function(attachment){
	if(!attachment)
		return '';
	attachment = Attachments.findOne({_id:attachment});
	return attachment.url();
  });
  Template.registerHelper('itemName',function(itemId){
      return Items.findOne({_id:itemId}).name;
  });
  
	Meteor.confirm = function(message,callback){
		return bootbox.dialog({
			message:message,
			buttons:{
				yes:{ 
					label: "כן",
					className: "btn-success",
					callback: function() {
						callback(true);
					}
				},
				no:{
					label: "לא",
					className: "btn-default",
					callback: function() {
						callback(false);
					}
				}
			}
		});
	}
	Meteor.alert = function(message,callback){
		return bootbox.dialog({
			message:message,
			buttons:{
				yes:{
					label: "סגור",
					className: "btn-default",
					callback: callback
				}
			}
		});
	};
	Date.prototype.toString = function(){
		return  moment(this).format('D/M/YYYY H:mm');
	}
	
	
	AutoForm.addHooks(null,{
		onSuccess:function(){
			history.back();
		}
	});

}).call(this);

