// Generated by CoffeeScript 1.4.0
(function() {

  this.Customers = new Meteor.Collection('customers');
   

  Schemas.Customers = new SimpleSchema({
	name:{
	  type: String,
	  unique:true,
	  max:30,
	  label:'שם'
	},
    email: {
      type: String,
	  unique:true,
      regEx: SimpleSchema.RegEx.Email,
	  label:'דוא"ל'
    },
	address: {
      type: String,
	  label:'כתובת'
    },
	phone:{
      type:String,
	  label:'טלפון'
	},
  });

  Customers.attachSchema(Schemas.Customers);

}).call(this);
