// Generated by CoffeeScript 1.4.0
(function () {

    Meteor.publish('suppliers', function () {
        return Suppliers.find();
    });

    Meteor.publish('items', function () {
        return Items.find();
    });

    Meteor.publish('customers', function () {
        return Customers.find();
    });

    Meteor.publish('workOrders', function () {
        return WorkOrders.find();
    });

    Meteor.publish('inventoryOrders', function () {
        return InventoryOrders.find();
    });

    Meteor.publish('rooms', function () {
        return Rooms.find();
    });

    Meteor.publish('attachments', function () {
        return Attachments.find();
    });

}).call(this);
