// Generated by CoffeeScript 1.4.0
(function () {
    var AdminConfig;

    AdminConfig = {
        name: Config.name,
        collections: {
            Rooms: {
                label: 'חדרים',
                color: 'red',
                icon: 'home',
                auxCollections: ['Items'],
                tableColumns: [
                    {
                        label: 'מק"ט',
                        name: 'mac'
                    }, {
                        label: 'שם',
                        name: 'name'
                    }
                ]
            },
            Items: {
                label: 'פריטים',
                color: 'green',
                icon: 'cogs',
                auxCollections: ['Suppliers'],
                tableColumns: [
                    {
                        label: 'מק"ט',
                        name: 'mac'
                    }, {
                        label: 'שם',
                        name: 'name'
                    }
                ],
                omitFields:['addedQuantity']
            },
            Suppliers: {
                label: 'מחסנים',
                color: 'yellow',
                icon: 'building',
                auxCollections: [],
                tableColumns: [
                    {
                        label: 'שם',
                        name: 'name'
                    }
                ]
            },
            Customers: {
                label: 'לקוחות',
                color: 'purple',
                icon: 'users',
                auxCollections: [],
                tableColumns: [
                    {
                        label: 'שם',
                        name: 'name'
                    }
                ]
            },
            WorkOrders: {
                label: 'הזמנות עבודה',
                color: 'blue',
                icon: 'file-word-o',
                auxCollections: ['Rooms', 'Customers'],
                omitFields:['closedBy','stages'],
                tableColumns: [
                    {
                        label: 'מספר',
                        name: 'id'
                    },
                    {
                        label: 'תאריך',
                        name: 'orderDate'
                    }

                ]
            },
            InventoryOrders: {
                label: 'הזמנות אספקה',
                color: 'gray',
                icon: 'file-excel-o',
                auxCollections: ['Suppliers', 'Items'],
                tableColumns: [
                    {
                        label: 'מספר',
                        name: 'id'
                    },
                    {
                        label: 'תאריך',
                        name: 'orderDate'
                    }

                ]
            }
        },
        dashboard: {
            homeUrl: '/inventory'
        },
        autoForm: {
            omitFields: ['createdAt', 'updatedAt', 'id', 'mac', 'creator']
        }
    };

    if (Meteor.isClient) {
        window.AdminConfig = AdminConfig;
    } else if (Meteor.isServer) {
        global.AdminConfig = AdminConfig;
    }

}).call(this);
